<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="SANITY__Register_User"
    errors="1" failures="0" hostname="" id="" package="SANITY__Register_User" skipped="0"
    tests="1" time="0.01000" timestamp="Thu, 03 Nov 2016 12:05:18 GMT">
  
    <testcase name="SANITY__Register_User" time="0.01000" assertions="0">
    </testcase>
      <system-err>
          Error while running [SANITY Register User / SANITY__Register_User]:

  ReferenceError: d is not defined
    at Object.module.exports.SANITY__Register_User (C:\dev\nightwatch\node_modules\nightwatch\SANITY__Register_User.js:14:12)
    at Module.call (C:\dev\nightwatch\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\dev\nightwatch\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\dev\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\dev\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\dev\nightwatch\node_modules\q\q.js:796:13)
    at C:\dev\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\dev\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\dev\nightwatch\node_modules\q\q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
      </system-err>
  
  
  </testsuite>
</testsuites>
